import "./globals.css";
import MainLayout from "../layout/MainLayout";

export const metadata = {
     title: "Next.js",
     description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
     return (
          <html>
               <body>
                    <MainLayout>{children}</MainLayout>
               </body>
          </html>
     );
}
