import "./globals.css";
import { Providers } from "../providers/Providers";

export const metadata = {
     title: "Next.js",
     description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
     return (
          <html lang="es">
               <body>
                    <Providers>{children}</Providers>
               </body>
          </html>
     );
}
